# Generated by Django 4.0 on 2022-01-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color_code',
            field=models.CharField(default=1, max_length=7, verbose_name='Color_code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
