# Generated by Django 4.0 on 2022-01-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_color_code_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='crossed_out',
            field=models.BooleanField(default=False, verbose_name='crossed'),
        ),
    ]
