# Generated by Django 4.0 on 2022-01-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_crossed_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='color_code',
            field=models.CharField(default='red', max_length=7, verbose_name='Color_code'),
        ),
    ]
