# Generated by Django 4.0 on 2022-01-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_color_alter_task_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='color_code',
        ),
    ]
