# Generated by Django 4.0 on 2022-01-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0008_remove_task_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(max_length=200, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=16, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Server_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='Name')),
                ('task', models.TextField(max_length=200, verbose_name='Task')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('crossed_out', models.BooleanField(default=False, verbose_name='crossed')),
                ('color', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green')], default='red', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Owners notes')),
            ],
            options={
                'verbose_name_plural': 'Задача',
            },
        ),
    ]
