# Generated by Django 4.0 on 2022-01-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_task_color_alter_task_task_alter_task_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server_board',
            options={'verbose_name_plural': 'Server board'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'My board'},
        ),
    ]
