# Generated by Django 4.0 on 2022-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(default='https://i.imgur.com/BoZwIXW.png', max_length=100, verbose_name='avatar_url'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=1, max_length=200, verbose_name='bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reaction_count',
            field=models.CharField(default=1, max_length=100, verbose_name='avatar_url'),
            preserve_default=False,
        ),
    ]
