# Generated by Django 4.0 on 2022-01-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0015_alter_userprofile_reaction_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_email',
            field=models.BooleanField(default=False, null=True, verbose_name='activat'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(default='https://i.imgur.com/BoZwIXW.png', max_length=100, null=True, verbose_name='avatar_url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='', max_length=300, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reaction_count',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='reaction_count'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
