# Generated by Django 4.0 on 2022-01-10 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_server_board_reaction_count_in_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server_board',
            name='reaction_count_in_post',
        ),
        migrations.AddField(
            model_name='server_board',
            name='reaction_count_in_post',
            field=models.ManyToManyField(null=True, related_name='reaction_count_in_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
