# Generated by Django 4.0 on 2022-01-10 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_remove_server_board_reaction_count_in_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_board',
            name='reaction_count_in_post',
            field=models.ManyToManyField(related_name='reaction_count_in_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
